name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Defaults & Misspelling
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.29
        args: --enable misspell