name: PII Go Module Test & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-release:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8070:8000
      kms:
        image: nsmithuk/local-kms
        ports:
          - 8090:8080
        # env:
        # options: >-
        #   --name=kms 
        #   --health-cmd "curl http://localhost:9000/kms/health/live"
      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Unit & Functional tests
        run: |
          make test
        env:
          DYNAMODB_ENDPOINT: http://localhost:8070
          KMS_ENDPOINT: http://localhost:8090
